
Parameters:
  OneTimePassword:
    Type: String
    Description: Password used on first login

Resources:
  CNCSStudents:
    Type: AWS::IAM::Group
    Properties:
      GroupName: CNCSStudents
  
  StudentAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: StudentAccess
      Groups:
        - !Ref CNCSStudents
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: ec2:*
          Effect: Allow
          Resource: "*"
        - Effect: Allow
          Action: elasticloadbalancing:*
          Resource: "*"
        - Effect: Allow
          Action: cloudwatch:*
          Resource: "*"
        - Effect: Allow
          Action: autoscaling:*
          Resource: "*"
        - Effect: Allow
          Action: iam:CreateServiceLinkedRole
          Resource: "*"
          Condition:
            StringEquals:
              iam:AWSServiceName:
              - autoscaling.amazonaws.com
              - ec2scheduled.amazonaws.com
              - elasticloadbalancing.amazonaws.com
              - spot.amazonaws.com
              - spotfleet.amazonaws.com
              - transitgateway.amazonaws.com
     


  exampleuser1:
    Type: AWS::IAM::User
    Properties:
      UserName: exampleuser1
      Groups:
      - !Ref CNCSStudents
      LoginProfile:
        Password:
          Ref: OneTimePassword
        PasswordResetRequired: true

  exampleuser2:
    Type: AWS::IAM::User
    Properties:
      UserName: exampleuser2
      Groups:
      - !Ref CNCSStudents
      LoginProfile:
        Password:
          Ref: OneTimePassword
        PasswordResetRequired: true
        
  